// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package main

type IntQueue struct {
	items []int
}

func (q *IntQueue) Push(s int) {
	q.items = append(q.items, s)
}

func (q *IntQueue) Pop() int {
	s := q.items[0]
	q.items = q.items[1:]
	return s
}

func (q *IntQueue) Size() int {
	return len(q.items)
}
