// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/greeter/greeter.proto

/*
Package greeter is a generated protocol buffer package.

It is generated from these files:
	proto/greeter/greeter.proto

It has these top-level messages:
	Request
	Response
*/
package greeter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GreeterService service

type GreeterService interface {
	Greet(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type greeterService struct {
	c    client.Client
	name string
}

func NewGreeterService(name string, c client.Client) GreeterService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "greeter"
	}
	return &greeterService{
		c:    c,
		name: name,
	}
}

func (c *greeterService) Greet(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GreeterService.Greet", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GreeterService service

type GreeterServiceHandler interface {
	Greet(context.Context, *Request, *Response) error
}

func RegisterGreeterServiceHandler(s server.Server, hdlr GreeterServiceHandler, opts ...server.HandlerOption) error {
	type greeterService interface {
		Greet(ctx context.Context, in *Request, out *Response) error
	}
	type GreeterService struct {
		greeterService
	}
	h := &greeterServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&GreeterService{h}, opts...))
}

type greeterServiceHandler struct {
	GreeterServiceHandler
}

func (h *greeterServiceHandler) Greet(ctx context.Context, in *Request, out *Response) error {
	return h.GreeterServiceHandler.Greet(ctx, in, out)
}
